//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsertRows
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int AGE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> SALARY { get; set; }
    }
}
